# Generated by Django 3.0.5 on 2020-05-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='hospitald',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hdoctors', to='basic_app.hospital'),
        ),
    ]
